# Generated by Django 5.2 on 2025-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discount_productdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=20, null=True),
        ),
    ]
