# Generated by Django 5.2 on 2025-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
