# Generated by Django 5.1.7 on 2025-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', max_length=200),
        ),
    ]
