# Generated by Django 5.1.7 on 2025-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
