# Generated by Django 5.1.7 on 2025-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
