# Generated by Django 5.1.7 on 2025-06-07 20:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
