# Generated by Django 5.2 on 2025-06-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
