# Generated by Django 5.1.7 on 2025-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_value',
            field=models.CharField(blank=True, null=True),
        ),
    ]
