# Generated by Django 5.1.7 on 2025-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
