# Generated by Django 5.2 on 2025-07-10 09:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_discount_value'),
        ('product', '0002_product_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_is_active',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_is_valid',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_start_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discount'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
